/* DO NOT EDIT THIS FILE - it is machine generated */

#include "TCPconnect.h"
#include <android/log.h>

#include<stdio.h>
#include<sys/types.h>
#include<netinet/in.h>
#include<string.h>
#include<sys/socket.h>
#include<stdlib.h>
#include<unistd.h>

#define MAXLINE 1024
#define SIZE sizeof(struct sockaddr_in)
/* Header for class app_android_server_TCPconnect */

struct sockaddr_in sv_addr;
struct sockaddr_in cl_addr;
int sockfd_connect;
int sockfd_listen;
int port_num;

char errmsg[MAXLINE];

JNIEXPORT jint JNICALL Java_app_android_server_TCPconnect_listen_1server
(JNIEnv *env, jobject obj, jint port) {
	port_num = port;
	if((sockfd_listen = socket(AF_INET, SOCK_STREAM, 0)) == -1)
	{
		// listen socket make error
		return -1;
	}
    
	sv_addr.sin_family = AF_INET;
	sv_addr.sin_addr.s_addr = htonl(INADDR_ANY);
	sv_addr.sin_port = htons(port);
    
	if(bind(sockfd_listen, (struct sockaddr *)&sv_addr, SIZE) == -1)
	{
		// bind failed
		return -2;
	}

	if(listen(sockfd_listen, 1) == -1)
	{
		// listen error
		return -3;
	}

	return 0;
}

JNIEXPORT jstring JNICALL Java_app_android_server_TCPconnect_accept_1client
(JNIEnv *env, jobject obj) {
	char clientIP[MAXLINE];
	jstring clientIP_jstr;
	int addrlen = sizeof(cl_addr);

	if((sockfd_connect = accept(sockfd_listen, (struct sockaddr *)&cl_addr, &addrlen)) ==-1)
    {
		// accept error
		return NULL;
	}

	memset(clientIP, 0x00, MAXLINE);
	strcpy(clientIP, inet_ntoa(cl_addr.sin_addr));
	clientIP_jstr = (*env)->NewStringUTF(env, clientIP);
	return clientIP_jstr;
}

/*
	int con;
	// char ip_addr[MAXLINE];
	const char *ip_addr;
	int len;

	len = (*env)->GetStringUTFLength(env, jstr_ip);
	ip_addr = (*env)->GetStringUTFChars(env, jstr_ip, NULL);
	if(ip_addr == NULL) {
		return -1;
	}
	//strcpy(ip_addr, str);

	if((sd=socket(AF_INET,SOCK_STREAM,IPPROTO_TCP))==-1)
	{
		printf("\nSocket problem");
		return -1;
	}

	bzero((char*)&cli,sizeof(cli));
	cli.sin_family = AF_INET;
	// printf("ENTER IP NO: ");    
	// gets(ip_addr);
	cli.sin_addr.s_addr = inet_addr(ip_addr);
	// printf("ENTER PORT NO: ");
	// scanf("%d",&port);
	cli.sin_port=htons(port);
	// cli.sin_addr.s_addr=htonl(INADDR_ANY);

	con=connect(sd,(struct sockaddr*)&cli,sizeof(cli));

	if(con==-1)
	{
		printf("\nConnection error");
		return -2;
	}
	return 0;
*/

JNIEXPORT jint JNICALL Java_app_android_server_TCPconnect_send_1msg
(JNIEnv *env, jobject obj, jbyteArray img) {
	char *temp;
	int len;

	//len = (*env)->GetStringUTFLength(env, jstr);
	//str = (*env)->GetStringUTFChars(env, jstr, NULL);
	//if(str == NULL) {
	//	return -1;
	//}

	// len = (*env)->GetArrayLength(env, img);
	// byte_img = (*env)->GetByteArrayElements(env, img, NULL);
	temp = jbyteArray2cstr(env, img, &len);
	if(len<=0)
		return -1;

	// strcpy(content, byte_img);

	return send(sockfd_connect, (char *)temp, len+1, 0);
}

JNIEXPORT jstring JNICALL Java_app_android_server_TCPconnect_recv_1msg
(JNIEnv *env, jclass jcls) {
	char content_recv[MAXLINE];
	int i;
	jstring str;

	memset(content_recv, 0x00, MAXLINE);
	i=recv(sockfd_connect,content_recv,MAXLINE,0);
	str = (*env)->NewStringUTF(env, content_recv);

	return str;
}

JNIEXPORT jint JNICALL Java_app_android_server_TCPconnect_close_1listenSocket
(JNIEnv *env, jobject obj) {
	close(sockfd_listen);
	return 0;
}

JNIEXPORT jint JNICALL Java_app_android_server_TCPconnect_close_1connectSocket
(JNIEnv *env, jobject obj) {
	close(sockfd_connect);
	return 0;
}

char *jbyteArray2cstr(JNIEnv *env, jbyteArray javaBytes, int* length) {
	/*
	size_t len;
	jbyte *nativeBytes;
	char *nativeStr;
	int i;

	len = (*env)->GetArrayLength(env, javaBytes);
	nativeBytes = (*env)->GetByteArrayElements(env, javaBytes, 0);

	nativeStr = (char*)malloc(len+1);
	for(i=0; i<len; i++)
		nativeStr[i] = nativeBytes[i];
	nativeStr[len] = '\0';

	// strncpy(nativeStr, (char*)nativeBytes,len);
	// nativeStr[len] = '\0';
	*length = len+1;

	test_str = (*env)->NewByteArray(env, len);
	// (*env)->SetByteArrayRegion(env, test_str, 0, len, (jbyte *)nativeStr);
	(*env)->SetByteArrayRegion(env, test_str, 0, len, nativeStr);

	(*env)->ReleaseByteArrayElements(env, javaBytes, nativeBytes, JNI_ABORT);
	return nativeStr;
	*/
	return NULL;
}