/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class app_android_server_TCPconnect */

#ifndef _Included_app_android_server_TCPconnect
#define _Included_app_android_server_TCPconnect
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     app_android_server_TCPconnect
 * Method:    set_ip_port
 * Signature: (Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_app_android_server_TCPconnect_set_1ip_1port
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     app_android_server_TCPconnect
 * Method:    send_msg
 * Signature: ([B)I
 */
JNIEXPORT jint JNICALL Java_app_android_server_TCPconnect_send_1msg
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     app_android_server_TCPconnect
 * Method:    recv_msg
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_app_android_server_TCPconnect_recv_1msg
  (JNIEnv *, jclass);

/*
 * Class:     app_android_server_TCPconnect
 * Method:    native_test
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_app_android_server_TCPconnect_native_1test
  (JNIEnv *, jobject);

char *jbyteArray2cstr (JNIEnv *, jbyteArray, int*);


#ifdef __cplusplus
}
#endif
#endif
